config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "/usuarios" => "users#index"
  get "/articulos" => "articles#index"
  get "/nuevo_usuario" => "users#new"
  get "/nuevo_articulo" => "articles#new"

  resources :users do
    resources :articles
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates_presence_of :title, lenght: { maximum: 50, too_long: "%{count} es el maximo de caracteres para el titulo" }
  validates_presence_of :content, length: { maximum: 200, too_long: "%{count} es el maximo de caracteres para el contenido" }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  validates_presence_of :name, lenght: { in: 3..40 , wrong_length: "La longitud del nombre debe estar entre 3 a 40 caracteres"}
  validates_presence_of :email, lenght: { maximum: 25  , too_long: "%{count} es el maximo de caracteres para el email"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @article = Article.all
  end

  def new
    @user = User.find(params[:user_id])
    @article = @user.articles.build
  end

  def create
    @user = User.find(params[:user_id])
    @article = @user.articles.build(article_params)

   if @article.save
     redirect_to articulos_path, notice: "AGREGADO CON EXITO"
   else
     flash[:errors] = "NO SE PUDO AGREGAR"
     render :new
   end
  end

  def show
    @article = Article.find_by (params[:id])
  end

  def edit
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articulos_path, notice: "ELIMINADO CON EXITO"
  end

  protected
  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

   if @user.save
     redirect_to users_path, notice: "USUARIO AGREGADO CON EXITO"
   else
     flash[:errors] = "NO SE PUDO AGREGAR USUARIO"
     render :new
   end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: "USUARIO ELIMINADO CON EXITO"
  end

  protected
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<tr>
  <td><%=article.id%></td>
  <td><%=article.title%></td>
  <td><%=article.content%></td>
</tr>

app/views/articles/_form.html.erb
<%= form_for [@user,article] do |f| %>
  <%if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
        <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
    </div>
  <% end %>

<center>
    <div class="form-group form-inline" align="center" >
      <center><b><%= f.label :title, "Titulo :" %></b></center>
      <%= f.text_field :title, size: 25,  class: "form-control" %>
    </div>
    <br>
    <div class="form-group form-inline" align="center" >
      <center><b><%= f.label :content, "Contenido :" %></b></center>
      <%= f.text_field :content, size: 25,  class: "form-control" %>
    </div>
    <br><br>
    <div class="btn-group" role="group">
        <%= f.submit "SAVE" ,class: "btn btn-primary btn-lg btn-block" %>
        <%= link_to "CANCEL",root_path, class: "btn btn-primary btn-lg btn-block" %>
    </div>
</center>

<%end%>

app/views/articles/index.html.erb
<br><br><br>
<div class="top-menu" >
	<ul class="nav pull-right 	top-menu">
		<li>
				<div class="btn-group" role="group">
					<%= link_to "BACK",root_path, class: "btn btn-primary btn-lg btn-block" %>
				</div>
		</li>
	</ul>
</div>

<center><h1>ARTICULOS</h1>
  <table border="5" class="table  table-striped">
  <thead>
		<th>ID_ARTICULO</th>
    <th>TITULO</th>
    <th>CONTENIDO</th>
  </thead>
  <tbody>
    <%=render @article %>
  </tbody>
</table></center>

app/views/articles/new.html.erb
<br><br><br>
<div>
  <center><h1>AÑADIR ARTICULO</h1></center>
  <%= render partial: "form", locals: {article: @article} %>
</div>

app/views/articles/show.html.erb
<center><table border="5" class="table  table-striped">
  <thead>
    <th>ID_ARTICULO</th>
    <th>TITULO</th>
    <th>CONTENIDO</th>
  </thead>
  <tbody>
    <%=render @article %>
  </tbody>
</table></center>

app/views/home/index.html.erb
<br><br><br><br>

<center><h1>Universidad Tecnologica de Honduras<h1>

<br><br>
<div class="btn-group" role="group">
  <%= button_to "REGISTRO DE USUARIOS ", usuarios_path, :method => :get ,class: "btn btn-default" %>
</div>

<br><br>
<div class="btn-group" role="group">
  <%= button_to "REGISTRO DE ARTICULOS", articulos_path, :method => :get ,class: "btn btn-default" %>
</div>

<br><br>
<div class="btn-group" role="group">
  <%= button_to "        NUEVO USUARIO       ", nuevo_usuario_path, :method => :get ,class: "btn btn-default" %>
</div>
<br>


</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tarea1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section id="container" class="sidebar-closed">
    <!--Nav Start-->
    <header class="header black-bg">
      <div class="top-menu" >
        <ul class="nav pull-right top-menu">
        </ul>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(usuario) do |f| %>
<center>
<div class="form-group form-inline" align="center" >
  <center><b><%= f.label :name, "Nombre :" %></b></center>
  <%= f.text_field :name, size: 25,  class: "form-control" %>
</div> <br>
<div class="form-group form-inline" align="center" >
  <center><b><%= f.label :email, "Email :" %></b></center>
  <%= f.text_field :email, size: 25,  class: "form-control" %>
</div> <br><br>
<div class="btn-group" role="group">
    <%= f.submit "SAVE" ,class: "btn btn-primary btn-lg btn-block" %> 
    <%= link_to "CANCEL",root_path, class: "btn btn-primary btn-lg btn-block" %>
</div></center>

<%end%>

app/views/users/_user.html.erb
<tr>
  <td><%= user.id %></td>
  <td><%= link_to user.name, user_path(user.id) %></td>
  <td><%= link_to "Agregar", new_user_article_path(user.id) %></td>
  <td><%= link_to "Borrar", user,class: "btn btn-default", method: :delete, data: {confirm: "Eliminar Usuario?"} %></td>
</tr>

app/views/users/index.html.erb
<br><br><br>
<div class="top-menu" >
	<ul class="nav pull-right 	top-menu">
		<li>
				<div class="btn-group" role="group">
					<%= link_to "BACK",root_path, class: "btn btn-primary btn-lg btn-block" %>
				</div>
		</li>
	</ul>
</div>
<center><h1>USUARIOS</h1>
<table border=1 class="table  table-striped" >
  <thead>
    <th>ID_USER</th>
    <th>NOMBRE</th>
    <th>AGREGAR ARTICULO</th>
    <th>BORRAR</th>
  </thead>

  <tbody>
    <%=render @user%>
  </tbody>

</table></center>

app/views/users/new.html.erb
<br><br><br><div>
<center><h1>AÑADIR USUARIO</h1></center>
<%= render partial: "form", locals: {usuario: @user} %>
</div>

app/views/users/show.html.erb
<br><br><br>

<h1>USUARIO</h1>
<table border="1" class="table  table-striped">
	<thead>
		<tr>
      <th>ID_Afiliado</th>
      <th>Nombre</th>
			<th>Borrar_Usuario</th>
		</tr>
	</thead>
	<tbody>
		<%= render @user %>
	</tbody>
</table>